name: Release .apk

on:
  push:
    tags:
      - 'v*'  # 예: v1.0.0, v2.1.3 등으로 태그를 push하면 동작

jobs:
  upload-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build .apk
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Build/*.apk
